### ISSUE TITLE
Support for service stacks? Any alternatives way to find the nginx-proxy container?

### ISSUE THREAD

**Issue by pjmolina** [zodern/nginx-proxy-swarm-upstream#1]
Hi. This is an amazing work. First of all, congrats!
I am trying to adapt it to work inside a docker service stack. So far, tested the following:

```
version: "3.6"

volumes:
  nginx-data:
services:
  nginx1:
    image: jwilder/nginx-proxy
    ports: 
      - 443:443
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro  
      - nginx-data:/etc/nginx
      - .certs/:/etc/nginx/certs
    deploy:
      placement:
          constraints:
            - node.labels.front == true

  nginx-upstream:
    image: zodern/nginx-proxy-swarm-upstream
    volumes:
      - nginx-data:/etc/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro  
    environment:
      NGINX_PROXY_CONTAINER: nginx1
    deploy:
      placement:
          constraints:
            - node.labels.front == true
...
```
I needed to remove the volumes-from (not supported in compose 3.0). But fixed with a shared volume.
On the other hand, the value of **NGINX_PROXY_CONTAINER** (**nginx1** in this case) is not helping, because in services, the final container name will change.

Therefore, the nginx-proxy-swarm-upstream fails with this trace:
```
t_nginx-upstream.1.qh4q3uzoljvn@command    | (node:1) UnhandledPromiseRejectionWarning: Error: connect ENOENT /var/run/docker.sock
t_nginx-upstream.1.k5pwh0ice2o9@command    | (node:1) UnhandledPromiseRejectionWarning: Error: connect ENOENT /var/run/docker.sock
t_nginx-upstream.1.k5pwh0ice2o9@command    |     at Object._errnoException (util.js:992:11)
t_nginx-upstream.1.qh4q3uzoljvn@command    |     at Object._errnoException (util.js:992:11)
t_nginx-upstream.1.qh4q3uzoljvn@command    |     at _exceptionWithHostPort (util.js:1014:20)
t_nginx-upstream.1.k5pwh0ice2o9@command    |     at _exceptionWithHostPort (util.js:1014:20)
t_nginx-upstream.1.k5pwh0ice2o9@command    |     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
t_nginx-upstream.1.qh4q3uzoljvn@command    |     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
t_nginx-upstream.1.qh4q3uzoljvn@command    | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
t_nginx-upstream.1.k5pwh0ice2o9@command    | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
t_nginx-upstream.1.k5pwh0ice2o9@command    | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
t_nginx-upstream.1.qh4q3uzoljvn@command    | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
t_nginx-upstream.1.qh4q3uzoljvn@command    | (node:1) UnhandledPromiseRejectionWarning: Error: connect ENOENT /var/run/docker.sock
t_nginx-upstream.1.k5pwh0ice2o9@command    | (node:1) UnhandledPromiseRejectionWarning: Error: connect ENOENT /var/run/docker.sock
t_nginx-upstream.1.k5pwh0ice2o9@command    |     at Object._errnoException (util.js:992:11)
t_nginx-upstream.1.qh4q3uzoljvn@command    |     at Object._errnoException (util.js:992:11)
t_nginx-upstream.1.qh4q3uzoljvn@command    |     at _exceptionWithHostPort (util.js:1014:20)
t_nginx-upstream.1.k5pwh0ice2o9@command    |     at _exceptionWithHostPort (util.js:1014:20)
t_nginx-upstream.1.k5pwh0ice2o9@command    |     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
t_nginx-upstream.1.qh4q3uzoljvn@command    |     at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
t_nginx-upstream.1.qh4q3uzoljvn@command    | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
t_nginx-upstream.1.k5pwh0ice2o9@command    | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Mi question is: **Is there another way to obtain the reference to nginx-proxy without relaying in the container name?**
For example, setting a specific env var or label in the nginx-proxy to found it in an indirect way?
